name: Docker Image CI

on:
  push:
    branches: [ docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Docker Publish
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: 
        # Tag for the Docker image
        tag: # optional
        # Script body to compute tag name for the Docker image, has context as the main function argument
        tag script: # optional
        # Username for Docker registry
        username: ${{ secrets.DOCKER_HUB_USER }}
        # Password for Docker registry
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        # Registry URL
        registry: # optional
        # Don't skip pull requests
        include pull requests: # optional
